services:
  pwpush:
    image: docker.io/pglombardo/pwpush:latest
    container_name: pwpusher
    restart: unless-stopped
    expose:
      - 5100
    environment:
      - PWPUSH_MASTER_KEY=${PWPUSH_MASTER_KEY}
      - TLS_DOMAIN=${TLS_DOMAIN}
      - VIRTUAL_HOST=${TLS_DOMAIN}
      - LETSENCRYPT_HOST=${TLS_DOMAIN}
      - VIRTUAL_PORT="5100"
      - PWP__DISABLE_LOGIN="true"
      - PWP__DISABLE_SIGNUPS="true"
      - PWP__BRAND__SHOW_FOOTER_MENU="false"
      - PWP_THEME="darkly"
    volumes:
      - ./pwpush-storage:/opt/PasswordPusher/storage
    networks:
      - web

networks:
  web:
    external: true
